lab1/FarmEquipmentShop/FarmEquipmentShop/Models/AccountModel.cs
namespace FarmEquipmentShop.Models
{
    public class AccountModel
    {
        public string Name { get; set; }
        public string Lastname { get; set; }
        public string Middlename {  get; set; }
        public string Email { get; set; }
        public string? Phone { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
    }
}

lab1/FarmEquipmentShop/FarmEquipmentShop/Models/ApplicationErrorModel.cs
namespace FarmEquipmentShop.Models
{
    public class ApplicationErrorModel
    {
        public List<string> Errors { get; set; }
    }
}

lab1/FarmEquipmentShop/FarmEquipmentShop/Models/ErrorViewModel.cs
namespace FarmEquipmentShop.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

lab1/FarmEquipmentShop/FarmEquipmentShop/Controllers/AccountController.cs
using FarmEquipmentShop.Models;
using FluentValidation;
using Microsoft.AspNetCore.Mvc;

namespace FarmEquipmentShop.Controllers
{
    public class AccountController : Controller
    {
        public readonly IValidator<AccountModel> _validator;

        public AccountController(IValidator<AccountModel> validator)
        {
            _validator = validator;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Save(AccountModel account)
        {
            var result = _validator.Validate(account);

            if (result.IsValid) 
            {
                return Redirect("~/");
            }

            var errors = new List<string>();

            foreach (var error in result.Errors) 
            {
                errors.Add(error.ErrorMessage);
            }

            return View("ApplicationError", new ApplicationErrorModel() { Errors = errors });
        }
    }
}

lab1/FarmEquipmentShop/FarmEquipmentShop/Controllers/EmailController.cs
using FarmEquipmentShop.DTOs;
using FarmEquipmentShop.Services;
using Microsoft.AspNetCore.Mvc;

namespace FarmEquipmentShop.Controllers
{
    public class EmailController : Controller
    {
        private readonly IEmailSenderService _emailSenderService;

        public EmailController(IEmailSenderService emailSenderService)
        {
            _emailSenderService = emailSenderService;
        }

        [HttpPost("email/send")]
        public IActionResult Send(EmailDTO emailDTO)
        {
            _emailSenderService.SendEmail(emailDTO.Email, "Test subject", "Test content");

            return Redirect("~/");
        }
    }
}

lab1/FarmEquipmentShop/FarmEquipmentShop/Controllers/FileController.cs
using FarmEquipmentShop.Services;
using Microsoft.AspNetCore.Mvc;

namespace FarmEquipmentShop.Controllers
{
    public class FileController : Controller
    {
        private readonly IFileService _fileService;

        public FileController(IFileService fileService)
        {
            _fileService = fileService;
        }

        public IActionResult Index()
        {
            var fileNameList = _fileService.ReadList();

            if (fileNameList == null)
            {
                return View("Error", Request);
            }

            return View(fileNameList);
        }

        [HttpGet]
        public IActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Upload(IFormFile file)
        {
            _fileService.Upload(file);

            return View(file);
        }

        public IActionResult Preview([FromQuery] string fileName) 
        {
            var preview = _fileService.Read(fileName, 1024);

            if (preview == null)
            {
                return View("Error", Request);
            }

            return View(preview);
        }
    }
}

lab1/FarmEquipmentShop/FarmEquipmentShop/Controllers/HomeController.cs
using FarmEquipmentShop.Models;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FarmEquipmentShop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
    }
}

lab1/FarmEquipmentShop/FarmEquipmentShop/ViewComponents/NavbarViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace FarmEquipmentShop.ViewComponents
{
    public class NavbarViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

lab1/FarmEquipmentShop/FarmEquipmentShop/Views/Shared/ApplicationError.cshtml
@model ApplicationErrorModel

<div class="container mt-5">
    <h1>Errors:</h1>

    @foreach(var error in Model.Errors)
    {
        <p>@error</p>
    }

</div>

lab1/FarmEquipmentShop/FarmEquipmentShop/Views/Shared/Components/Navbar/Default.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = Localizer["Title"];
    ViewData["Home"] = Localizer["Home"];
    ViewData["About"] = Localizer["About"];
    ViewData["Files"] = Localizer["Files"];
    ViewData["Shop"] = Localizer["Shop"];
    ViewData["AllProducts"] = Localizer["AllProducts"];
    ViewData["PopularItems"] = Localizer["PopularItems"];
    ViewData["NewArrivals"] = Localizer["NewArrivals"];
    ViewData["Cart"] = Localizer["Cart"];
    ViewData["Account"] = Localizer["Account"];
}

<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="#!">@ViewData["Title"]</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">@ViewData["Home"]</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">@ViewData["About"]</a></li>
                <li class="nav-item"><a class="nav-link" asp-controller="File" asp-action="Index">@ViewData["Files"]</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">@ViewData["Shop"]</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#!">@ViewData["AllProducts"]</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="#!">@ViewData["PopularItems"]</a></li>
                        <li><a class="dropdown-item" href="#!">@ViewData["NewArrivals"]</a></li>
                    </ul>
                </li>
                <li><a class="nav-link" asp-action="Index" asp-controller="Account">@ViewData["Account"]</a></li>
                <li class="nav-item">
                    @await Html.PartialAsync("_LanguagePartial")
                </li>
            </ul>
            <form class="d-flex">
                <button class="btn btn-outline-dark" type="submit">
                    <i class="bi-cart-fill me-1"></i>
                    @ViewData["Cart"]
                    <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                </button>
            </form>
        </div>
    </div>
</nav>

lab1/FarmEquipmentShop/FarmEquipmentShop/Views/Shared/_LanguagePartial.cshtml
@using Microsoft.Extensions.Options
@using Microsoft.AspNetCore.Localization;

@inject IOptions<RequestLocalizationOptions> LocOptions
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}

<div>
    <form asp-controller="Home"
          asp-action="SetLanguage"
          asp-route-returnUrl="@Context.Request.Path" method="post" class="nav-link">
        <select name="culture" onchange="this.form.submit();"
                asp-for="@requestCulture.RequestCulture.UICulture.Name"
                asp-items="cultureItems" class="form-select-sm">
        </select>
    </form>
</div>

lab1/FarmEquipmentShop/FarmEquipmentShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <title>FarmEquipmentShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/FarmEquipmentShop.styles.css" asp-append-version="true" />
</head>
<body>
    <vc:navbar/>
  
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Core theme JS-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>